(()=>{
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const sims=[
 ['Le Mans Ultimate','LMU','Endurance, Hypercar, LMP2 y LMGT3'],
 ['RaceRoom','RaceRoom','Ranked, touring, DTM y multicategoría'],
 ['Assetto Corsa EVO','AC EVO','Novedades, daily races y evolución del simulador'],
 ['Assetto Corsa Rally','AC Rally','Rally, coches clásicos y actualizaciones'],
 ['Automobilista 2','AMS2','Contenido, físicas y carreras multiclase'],
 ['Euro Truck Simulator 2','ETS2','Actualizaciones, DLC y comunidad'],
 ['American Truck Simulator','ATS','Estados, DLC y novedades'],
 ['Hardware','Hardware','SRP, OneSimPro y equipamiento de SimRacing']
];
function addStyle(){if(document.querySelector('link[href="/portal-next.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/portal-next.css';document.head.appendChild(l)}
function enhanceEvents(){const sec=document.querySelector('#eventos');if(!sec||sec.querySelector('.portal-actions'))return;const a=document.createElement('div');a.className='portal-actions';a.innerHTML='<a class="portal-action primary" href="/donde-correr.html">Abrir agenda completa →</a><a class="portal-action" href="/simulador.html?sim=Le%20Mans%20Ultimate">Ver página LMU</a>';const agenda=sec.querySelector('#agenda');if(agenda)agenda.after(a);else sec.appendChild(a)}
function addSimulatorHub(){if(document.querySelector('#simHub'))return;const osp=document.querySelector('#osp');if(!osp)return;const sec=document.createElement('section');sec.id='simHub';sec.className='sec sim-hub';sec.innerHTML=`<div class="head"><div><span class="ey">SIMULADORES</span><h2>Tu portal por simulador</h2></div><p>Noticias y carreras agrupadas en una sola página</p></div><div class="sim-hub-grid">${sims.map(([name,label,desc])=>`<a class="sim-hub-card" href="/simulador.html?sim=${encodeURIComponent(name)}"><small>${esc(desc)}</small><b>${esc(label)}</b><span>Abrir sección →</span></a>`).join('')}</div>`;osp.after(sec)}
function addRacing(){if(document.querySelector('#oscarRacing'))return;const canales=document.querySelector('#canales');if(!canales)return;const sec=document.createElement('section');sec.id='oscarRacing';sec.className='sec racing-section';sec.innerHTML='<div class="head"><div><span class="ey">OSCAR RISAN RACING</span><h2>Próximas carreras y contenido</h2></div><p>Mi actividad competitiva dentro del portal</p></div><div class="racing-grid"><div class="racing-main"><span class="ey">PRÓXIMAMENTE</span><h3>Mis siguientes eventos</h3><p>Este bloque toma los próximos eventos publicados en la agenda y prioriza el contenido de competición para tenerlo localizado sin buscar por toda la web.</p><div class="racing-next" id="racingNext"><div class="empty">Cargando próximos eventos…</div></div></div><div class="racing-side"><span class="ey">CONTENIDO</span><h3>Oscar Risan</h3><div class="racing-links"><a href="https://www.twitch.tv/oscarrisan" target="_blank"><div><b>Twitch</b><small>Directos y carreras en vivo</small></div><span>→</span></a><a href="https://www.youtube.com/@oscarrisansimracing6480" target="_blank"><div><b>YouTube</b><small>Vídeos, carreras y resúmenes</small></div><span>→</span></a><a href="https://x.com/oscarrisan" target="_blank"><div><b>X</b><small>Previas, resultados y clips</small></div><span>→</span></a></div></div></div>';canales.before(sec);
 fetch('/api/events').then(r=>r.json()).then(d=>{const now=Date.now();const items=(d.items||[]).filter(e=>new Date(e.start).getTime()>=now).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,4);const el=document.querySelector('#racingNext');if(!el)return;el.innerHTML=items.length?items.map(e=>`<div class="racing-item"><div class="racing-time">${new Date(e.start).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}</div><div><b>${esc(e.title)}</b><small>${new Date(e.start).toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'})} · ${esc(e.track||'')} · ${esc(e.duration||'')}</small></div><span class="racing-pill">${esc(e.label||e.sim||'Evento')}</span></div>`).join(''):'<div class="empty">No hay próximos eventos publicados ahora mismo.</div>'}).catch(()=>{const el=document.querySelector('#racingNext');if(el)el.innerHTML='<div class="empty">No se pudieron cargar los próximos eventos.</div>'})}
function featured(){if(document.querySelector('#featuredNews'))return;const noticias=document.querySelector('#noticias');if(!noticias)return;fetch('/api/news').then(r=>r.json()).then(d=>{const n=(d.items||[])[0];if(!n)return;const sec=document.createElement('section');sec.id='featuredNews';sec.className='featured-news';sec.innerHTML=`<div class="featured-news-inner"><a class="featured-media" href="/article.html?id=${encodeURIComponent(n.id)}">${n.image?`<img src="${esc(n.image)}" alt="" onerror="this.remove()">`:''}</a><div class="featured-copy"><span class="featured-label">NOTICIA DESTACADA · ${esc(n.category||'SIMRACING')}</span><div class="featured-meta">${esc(n.source||'Fuente oficial')} ${n.date?'· '+new Date(n.date).toLocaleDateString('es-ES'):''}</div><h2><a href="/article.html?id=${encodeURIComponent(n.id)}">${esc(n.title)}</a></h2><p>${esc(n.summary||'')}</p><a class="portal-action primary" href="/article.html?id=${encodeURIComponent(n.id)}">Leer noticia →</a></div></div>`;noticias.before(sec)}).catch(()=>{})}
function addNav(){const nav=document.querySelector('header.top nav');if(!nav||nav.querySelector('a[href="/donde-correr.html"]'))return;const a=document.createElement('a');a.href='/donde-correr.html';a.textContent='Agenda+';nav.insertBefore(a,nav.firstChild);const r=document.createElement('a');r.href='#oscarRacing';r.textContent='Racing';nav.appendChild(r)}
addStyle();enhanceEvents();addSimulatorHub();addRacing();featured();addNav();
})();