(()=>{
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const sims=[
 ['Le Mans Ultimate','LMU','Endurance, Hypercar, LMP2 y LMGT3'],
 ['RaceRoom','RaceRoom','Ranked, touring, DTM y multicategoría'],
 ['Assetto Corsa EVO','AC EVO','Novedades, daily races y evolución del simulador'],
 ['Assetto Corsa Rally','AC Rally','Rally, coches clásicos y actualizaciones'],
 ['Automobilista 2','AMS2','Contenido, físicas y carreras multiclase'],
 ['Euro Truck Simulator 2','ETS2','Actualizaciones, DLC y comunidad'],
 ['American Truck Simulator','ATS','Estados, DLC y novedades'],
 ['Hardware','Hardware','SRP, OneSimPro y equipamiento de SimRacing']
];
const FAV_KEY='or-favorite-sims-v1';
function getFavs(){try{const v=JSON.parse(localStorage.getItem(FAV_KEY)||'[]');return Array.isArray(v)?v.filter(x=>sims.some(s=>s[0]===x)):[]}catch{return[]}}
function saveFavs(v){try{localStorage.setItem(FAV_KEY,JSON.stringify(v))}catch{}}
function addSEO(){
 const title='Oscar Risan SimRacing · Noticias, carreras y hardware';
 const desc='Noticias de SimRacing en castellano, Agenda+ de carreras, LMU, RaceRoom, Assetto Corsa, AMS2, hardware, SRP, OneSimPro y contenido de Oscar Risan.';
 const image='https://oscar-risan-simracing-portal.vercel.app/api/og';
 const up=(sel,tag,attrs)=>{let el=document.head.querySelector(sel);if(!el){el=document.createElement(tag);document.head.appendChild(el)}Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el};
 document.title=title;up('meta[name="description"]','meta',{name:'description',content:desc});up('meta[name="robots"]','meta',{name:'robots',content:'index,follow,max-image-preview:large'});up('link[rel="canonical"]','link',{rel:'canonical',href:'https://oscar-risan-simracing-portal.vercel.app/'});up('meta[property="og:site_name"]','meta',{property:'og:site_name',content:'Oscar Risan SimRacing'});up('meta[property="og:locale"]','meta',{property:'og:locale',content:'es_ES'});up('meta[property="og:type"]','meta',{property:'og:type',content:'website'});up('meta[property="og:title"]','meta',{property:'og:title',content:title});up('meta[property="og:description"]','meta',{property:'og:description',content:desc});up('meta[property="og:url"]','meta',{property:'og:url',content:'https://oscar-risan-simracing-portal.vercel.app/'});up('meta[property="og:image"]','meta',{property:'og:image',content:image});up('meta[name="twitter:card"]','meta',{name:'twitter:card',content:'summary_large_image'});up('meta[name="twitter:title"]','meta',{name:'twitter:title',content:title});up('meta[name="twitter:description"]','meta',{name:'twitter:description',content:desc});up('meta[name="twitter:image"]','meta',{name:'twitter:image',content:image});
 if(!document.head.querySelector('script[data-or-schema]')){const s=document.createElement('script');s.type='application/ld+json';s.dataset.orSchema='1';s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'Oscar Risan SimRacing',url:'https://oscar-risan-simracing-portal.vercel.app/',inLanguage:'es'});document.head.appendChild(s)}
}
function addStyle(){if(document.querySelector('link[href="/portal-next.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/portal-next.css';document.head.appendChild(l)}
function loadAnalytics(){if(document.querySelector('script[src="/analytics.js"]'))return;const s=document.createElement('script');s.src='/analytics.js';s.defer=true;document.body.appendChild(s)}
function loadToday(){if(document.querySelector('script[src="/hoy.js"]'))return;const s=document.createElement('script');s.src='/hoy.js';s.defer=true;document.body.appendChild(s)}
function loadWeek(){if(document.querySelector('script[src="/semana.js"]'))return;const s=document.createElement('script');s.src='/semana.js';s.defer=true;document.body.appendChild(s)}
function enhanceEvents(){const sec=document.querySelector('#eventos');if(!sec||sec.querySelector('.portal-actions'))return;const a=document.createElement('div');a.className='portal-actions';a.innerHTML='<a class="portal-action primary" href="/donde-correr.html">Abrir agenda completa →</a><a class="portal-action" href="/simulador.html?sim=Le%20Mans%20Ultimate">Ver página LMU</a>';const agenda=sec.querySelector('#agenda');if(agenda)agenda.after(a);else sec.appendChild(a)}
function favoritePanel(){const hub=document.querySelector('#simHub');if(!hub||hub.querySelector('.fav-panel'))return;const grid=hub.querySelector('.sim-hub-grid');if(!grid)return;const panel=document.createElement('div');panel.className='fav-panel';panel.innerHTML='<div class="fav-head"><div><span class="ey">MIS SIMULADORES</span><b>Elige tus favoritos</b></div><small>Se guardan solo en este navegador</small></div><div class="fav-controls"></div><div class="fav-links"></div>';
 grid.before(panel);const controls=panel.querySelector('.fav-controls'),links=panel.querySelector('.fav-links');
 function render(){const favs=getFavs();controls.innerHTML=sims.map(([name,label])=>`<button type="button" class="fav-chip ${favs.includes(name)?'active':''}" data-sim="${esc(name)}" aria-pressed="${favs.includes(name)?'true':'false'}">${favs.includes(name)?'★':'☆'} ${esc(label)}</button>`).join('');links.innerHTML=favs.length?`<span>Acceso rápido:</span>${favs.map(name=>{const x=sims.find(s=>s[0]===name);return `<a href="/simulador.html?sim=${encodeURIComponent(name)}">${esc(x?.[1]||name)} →</a>`}).join('')}`:'<span>Marca uno o varios simuladores para tenerlos aquí a mano.</span>'}
 controls.addEventListener('click',e=>{const b=e.target.closest('button[data-sim]');if(!b)return;const name=b.dataset.sim;let favs=getFavs();favs=favs.includes(name)?favs.filter(x=>x!==name):[...favs,name];saveFavs(favs);render()});render()}
function addSimulatorHub(){if(document.querySelector('#simHub'))return;const osp=document.querySelector('#osp');if(!osp)return;const sec=document.createElement('section');sec.id='simHub';sec.className='sec sim-hub';sec.innerHTML=`<div class="head"><div><span class="ey">SIMULADORES</span><h2>Tu portal por simulador</h2></div><p>Noticias y carreras agrupadas en una sola página</p></div><div class="sim-hub-grid">${sims.map(([name,label,desc])=>`<a class="sim-hub-card" href="/simulador.html?sim=${encodeURIComponent(name)}"><small>${esc(desc)}</small><b>${esc(label)}</b><span>Abrir sección →</span></a>`).join('')}</div>`;osp.after(sec);favoritePanel()}
function addRacing(){if(document.querySelector('#oscarRacing'))return;const canales=document.querySelector('#canales');if(!canales)return;const sec=document.createElement('section');sec.id='oscarRacing';sec.className='sec racing-section';sec.innerHTML='<div class="head"><div><span class="ey">OSCAR RISAN RACING</span><h2>Próximas carreras y contenido</h2></div><p>Mi actividad competitiva dentro del portal</p></div><div class="racing-grid"><div class="racing-main"><span class="ey">PRÓXIMAMENTE</span><h3>Mis siguientes eventos</h3><p>Este bloque toma los próximos eventos publicados en la agenda y prioriza el contenido de competición para tenerlo localizado sin buscar por toda la web.</p><div class="racing-next" id="racingNext"><div class="empty">Cargando próximos eventos…</div></div></div><div class="racing-side"><span class="ey">CONTENIDO</span><h3>Oscar Risan</h3><div class="racing-links"><a href="https://www.twitch.tv/oscarrisan" target="_blank"><div><b>Twitch</b><small>Directos y carreras en vivo</small></div><span>→</span></a><a href="https://www.youtube.com/@oscarrisansimracing6480" target="_blank"><div><b>YouTube</b><small>Vídeos, carreras y resúmenes</small></div><span>→</span></a><a href="https://x.com/oscarrisan" target="_blank"><div><b>X</b><small>Previas, resultados y clips</small></div><span>→</span></a></div></div></div>';canales.before(sec);
 fetch('/api/events').then(r=>r.json()).then(d=>{const now=Date.now();const items=(d.items||[]).filter(e=>new Date(e.start).getTime()>=now).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,4);const el=document.querySelector('#racingNext');if(!el)return;el.innerHTML=items.length?items.map(e=>`<div class="racing-item"><div class="racing-time">${new Date(e.start).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}</div><div><b>${esc(e.title)}</b><small>${new Date(e.start).toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'})} · ${esc(e.track||'')} · ${esc(e.duration||'')}</small></div><span class="racing-pill">${esc(e.label||e.sim||'Evento')}</span></div>`).join(''):'<div class="empty">No hay próximos eventos publicados ahora mismo.</div>'}).catch(()=>{const el=document.querySelector('#racingNext');if(el)el.innerHTML='<div class="empty">No se pudieron cargar los próximos eventos.</div>'})}
function featured(){if(document.querySelector('#featuredNews'))return;const noticias=document.querySelector('#noticias');if(!noticias)return;fetch('/api/news').then(r=>r.json()).then(d=>{const n=(d.items||[])[0];if(!n)return;const sec=document.createElement('section');sec.id='featuredNews';sec.className='featured-news';sec.innerHTML=`<div class="featured-news-inner"><a class="featured-media" href="/article.html?id=${encodeURIComponent(n.id)}">${n.image?`<img src="${esc(n.image)}" alt="" onerror="this.remove()">`:''}</a><div class="featured-copy"><span class="featured-label">NOTICIA DESTACADA · ${esc(n.category||'SIMRACING')}</span><div class="featured-meta">${esc(n.source||'Fuente oficial')} ${n.date?'· '+new Date(n.date).toLocaleDateString('es-ES'):''}</div><h2><a href="/article.html?id=${encodeURIComponent(n.id)}">${esc(n.title)}</a></h2><p>${esc(n.summary||'')}</p><a class="portal-action primary" href="/article.html?id=${encodeURIComponent(n.id)}">Leer noticia →</a></div></div>`;noticias.before(sec)}).catch(()=>{})}
function addNav(){const nav=document.querySelector('header.top nav');if(!nav)return;if(!nav.querySelector('a[href="/buscar.html"]')){const s=document.createElement('a');s.href='/buscar.html';s.textContent='Buscar';nav.insertBefore(s,nav.firstChild)}if(!nav.querySelector('a[href="/donde-correr.html"]')){const a=document.createElement('a');a.href='/donde-correr.html';a.textContent='Agenda+';nav.insertBefore(a,nav.firstChild)}if(!nav.querySelector('a[href="#oscarRacing"]')){const r=document.createElement('a');r.href='#oscarRacing';r.textContent='Racing';nav.appendChild(r)}}
addSEO();addStyle();loadAnalytics();loadToday();loadWeek();enhanceEvents();addSimulatorHub();favoritePanel();addRacing();featured();addNav();
})();