const RC='https://www.racecontrol.gg/';
const LMU_SPECIAL='https://lemansultimate.com/special-events-calendar-q3-4-2026/';
const ACEVO='https://acevo.gg/daily-races';
const RR_STEAM='https://steamcommunity.com/app/211500/announcements/';
const RR_API='https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/?appid=211500&count=20&maxlength=24000&format=json';
const headers={'user-agent':'Mozilla/5.0 OscarRisanSimRacing/3.0'};
const nowIso=()=>new Date().toISOString();
function decode(s=''){return String(s).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&ndash;|&mdash;/g,'–').replace(/&nbsp;/g,' ')}
function text(html=''){return decode(html).replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<(br|\/p|\/div|\/li|\/h[1-6])[^>]*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n[ \t]+/g,'\n').replace(/\n{2,}/g,'\n').trim()}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
async function fetchText(url){const r=await fetch(url,{headers,signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`${r.status} ${url}`);return await r.text()}
function madridDateParts(d=new Date()){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]))}
function madridOffsetFor(y,m,d,h=12,min=0){const probe=new Date(Date.UTC(y,m-1,d,h,min));const z=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Madrid',timeZoneName:'longOffset',hour:'2-digit'}).formatToParts(probe).find(x=>x.type==='timeZoneName')?.value||'GMT+01:00';return z.replace('GMT','')}
function localIso(y,m,d,h=12,min=0){return new Date(`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}T${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}:00${madridOffsetFor(y,m,d,h,min)}`).toISOString()}
function localIsoToday(h,min){const p=madridDateParts();return localIso(+p.year,+p.month,+p.day,h,min)}
function mondayMadrid(){const n=new Date(), parts=madridDateParts(n);const d=new Date(`${parts.year}-${parts.month}-${parts.day}T12:00:00+02:00`);const dow=(d.getDay()+6)%7;d.setDate(d.getDate()-dow);d.setHours(12,0,0,0);return d}
function durationMin(s=''){let n=0;const h=s.match(/(\d+)\s*h(?:our)?/i);const m=s.match(/(\d+)\s*m(?:in)?/i);if(h)n+=+h[1]*60;if(m)n+=+m[1];return n||60}
function typeFrom(s=''){s=s.toLowerCase();if(/endurance|super\s*60|wec-xperience|\b[468]|10|24\s*hours/.test(s))return'endurance';if(/sprint|fixed|cup/.test(s))return'sprint';return'special'}
function tagsFrom(s=''){const out=['OFICIAL'];if(/multiclass|hypercar.*lmp|lmp.*lmgt|lmp3.*lmgt/i.test(s))out.unshift('MULTICLASE');const t=typeFrom(s);out.unshift(t==='endurance'?'ENDURANCE':t==='sprint'?'SPRINT':'ESPECIAL');return [...new Set(out)]}
function imgFor(sim,track=''){const t=track.toLowerCase();if(/spa/.test(t))return'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80';if(/le mans/.test(t))return'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80';if(/laguna|daytona|sebring|watkins/.test(t))return'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80';if(sim==='RaceRoom')return'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80';return'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80'}
function parseClock12(label=''){const m=label.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);if(!m)return null;let h=+m[1],min=+m[2];if(m[3].toUpperCase()==='PM'&&h<12)h+=12;if(m[3].toUpperCase()==='AM'&&h===12)h=0;return{h,min}}

async function raceControlDaily(){
 const t=text(await fetchText(RC));let zone=t.split(/Upcoming Daily Races/i)[1]||'';zone=zone.split(/Upcoming Daily Races|Featured Community Events|Latest Event Listings/i)[0]||zone;
 const rx=/(beginner|intermediate|advanced)\s*\n([^\n]{3,100})\s*\nDuration\s*\n([^\n]{2,40})\s*\nTrack\s*\n([^\n]{2,100})\s*\n([\s\S]*?)(?=\n(?:beginner|intermediate|advanced)\s*\n|$)/gi;
 const events=[];let m;const p=madridDateParts(),year=+p.year,months={Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12};
 while((m=rx.exec(zone))){const level=m[1],title=m[2].trim(),duration=m[3].trim(),track=m[4].trim(),times=m[5],tr=/(\d{1,2})\s+([A-Z][a-z]{2})\s+at\s+(\d{1,2})(?::(\d{2}))?(am|pm)/g;let tm,addedToday=false;
  while((tm=tr.exec(times))){let hh=+tm[3],mm=+(tm[4]||0);if(tm[5].toLowerCase()==='pm'&&hh<12)hh+=12;if(tm[5].toLowerCase()==='am'&&hh===12)hh=0;let y=year;const mon=months[tm[2]];if(mon<+p.month-6)y++;const start=localIso(y,mon,+tm[1],hh,mm);if(+tm[1]===+p.day&&mon===+p.month)addedToday=true;events.push({id:'rc-'+hash(title+track+start),sim:'Le Mans Ultimate',label:'LMU',title,track,duration,durationMin:durationMin(duration),start,level,timeLabel:`${tm[1]} ${tm[2]} · ${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`,tags:[level.toUpperCase(),...tagsFrom(title)],type:typeFrom(title),weather:'Según evento',fuel:'',tyres:'',img:imgFor('LMU',track),source:'RaceControl',sourceUrl:RC,lastUpdated:nowIso(),liveSource:true,details:{format:'Daily Race'}})}
  if(!addedToday){const start=localIso(+p.year,+p.month,+p.day,12,0);events.push({id:'rc-current-'+hash(title+track+start),sim:'Le Mans Ultimate',label:'LMU',title,track,duration,durationMin:durationMin(duration),start,level,timeLabel:'Combinación diaria vigente · horarios en RaceControl',tags:[level.toUpperCase(),...tagsFrom(title)],type:typeFrom(title),weather:'Según evento',fuel:'',tyres:'',img:imgFor('LMU',track),source:'RaceControl',sourceUrl:RC,lastUpdated:nowIso(),liveSource:true,details:{format:'Daily Race',note:'RaceControl no mostraba una sesión con hora de hoy en el bloque público consultado; se muestra la combinación diaria vigente sin asignar una hora exacta.'}})}
 }
 return events;
}
function currentYearForMonth(month){const p=madridDateParts();let y=+p.year,cur=+p.month;if(month<cur-6)y++;else if(month>cur+6)y--;return y}
async function lmuSpecial(){const t=text(await fetchText(LMU_SPECIAL)),events=[];const rx=/w\/c\s*(\d{1,2})\/(\d{1,2})\s*[–-]\s*(\d+)\s*Hours?\s+([^\n–]+?)\s*[–-]\s*([^\n]+)/gi;let m;while((m=rx.exec(t))){const day=+m[1],month=+m[2],hours=+m[3],track=m[4].trim(),classes=m[5].trim(),year=currentYearForMonth(month),start=localIso(year,month,day,12,0);if(new Date(start)<new Date(Date.now()-8*864e5))continue;events.push({id:'lmus-'+hash(start+track),sim:'Le Mans Ultimate',label:'LMU',title:`${hours} Horas · ${classes}`,track,duration:`${hours} h`,durationMin:hours*60,start,datePrecision:'week',timeLabel:'Horario por confirmar',tags:['EVENTO ESPECIAL',...tagsFrom(classes+' '+hours+' Hours')],type:'endurance',weather:'Por confirmar',fuel:'',tyres:'',img:imgFor('LMU',track),source:'Le Mans Ultimate',sourceUrl:LMU_SPECIAL,lastUpdated:nowIso(),liveSource:true,details:{format:'Evento especial'}})}return events}

async function assettoCorsaEvoDaily(){const t=text(await fetchText(ACEVO)),events=[],zone=t.split(/Browse Events/i)[1]||t;const rx=/(Championship|Quick Race)\s+Free\s*\n([^\n]{3,100})\s*\n([\s\S]*?)(?=\n(?:Championship|Quick Race)\s+Free\s*\n|$)/gi;let m;while((m=rx.exec(zone))){const format=m[1].trim(),title=m[2].trim(),block=m[3],practice=block.match(/(\d+)\s*min\s*Practice/i)?.[1],quali=block.match(/(\d+)\s*min\s*Qualifying/i)?.[1],race=block.match(/(\d+)\s*min\s*Race/i)?.[1],laps=block.match(/(\d+)\s*laps?\s*Race/i)?.[1],conditions=block.match(/Conditions\s*\n([^\n]+)/i)?.[1]?.trim()||'',track=block.match(/Track\s*\n([^\n]+)/i)?.[1]?.trim()||'',klass=block.match(/Class\s*\n([^\n]+)/i)?.[1]?.trim()||'';if(!track||!klass)continue;const schedule=(block.split(/Upcoming Races/i)[1]||''),times=[...schedule.matchAll(/(\d{1,2}:\d{2}\s*(?:AM|PM))/gi)].map(x=>x[1]);const duration=race?`${race} min carrera`:laps?`${laps} vueltas`:'Carrera diaria',type=/GT3|GT4|Cup|Sprint/i.test(title+' '+klass)?'sprint':'special';for(const tl of times.slice(0,10)){const c=parseClock12(tl);if(!c)continue;const start=localIsoToday(c.h,c.min);events.push({id:'ace-'+hash(title+track+start),sim:'Assetto Corsa EVO',label:'AC EVO',title:`${title} · ${klass}`,track,duration,durationMin:(+(practice||0))+(+(quali||0))+(+(race||0))||20,start,timeLabel:tl,tags:[format.toUpperCase(),type==='sprint'?'SPRINT':'DAILY','RANKED','OFICIAL'],type,weather:conditions,fuel:'',tyres:'',img:imgFor('Assetto Corsa EVO',track),source:'Assetto Corsa EVO · Daily Racing',sourceUrl:ACEVO,lastUpdated:nowIso(),liveSource:true,details:{practice:practice?`${practice} min`:null,qualifying:quali?`${quali} min`:null,race:duration,format}})}}return events}

function parseRRBlock(t,published,url){const events=[];const weekBase=mondayMadrid(),next=new Date(weekBase.getTime()+7*864e5),base=new Date();base.setHours(0,0,0,0);const ageDays=Math.round((Date.now()-published.getTime())/864e5);const stale=ageDays>9;const add=(title,track,kind='SPRINT',dayOffset=0,timeLabel='Disponible durante la semana')=>{title=(title||'').trim();track=(track||'').trim();if(!title||!track)return;const start=new Date(base.getTime()+dayOffset*864e5),key=title+'|'+track+'|'+kind;if(events.some(e=>e._key===key))return;const tags=[kind==='WEEKLY'?'WEEKLY':kind==='FEATURE'?'FEATURE':'SPRINT','RANKED','OFICIAL'];if(stale)tags.unshift('ÚLTIMO CALENDARIO OFICIAL');events.push({_key:key,id:'rr-'+hash(key),sim:'RaceRoom',label:'R3E',title,track,duration:kind==='WEEKLY'?'Weekly Race':kind==='FEATURE'?'Feature Race':'Sprint Race',durationMin:60,start:start.toISOString(),end:new Date(next.getTime()-1).toISOString(),datePrecision:'range',timeLabel:stale?'Último calendario oficial disponible':timeLabel,tags,type:kind==='SPRINT'?'sprint':'special',weather:'',fuel:'',tyres:'',img:imgFor('RaceRoom',track),source:'RaceRoom · Steam oficial',sourceUrl:url||RR_STEAM,lastUpdated:nowIso(),liveSource:true,details:{format:kind==='WEEKLY'?'Weekly Race':kind==='FEATURE'?'Feature Race':'Sprint Race',sourcePublished:published.toISOString(),note:stale?'La última publicación oficial accesible es anterior a esta semana. Se muestra como referencia, no como confirmación de vigencia.':null}})};
 const sections=[{name:'SPRINT',re:/Ranked Sprint Races([\s\S]*?)(?=Ranked Feature Races|Ranked Weekly Races|Free 2 Play Weekly Race|Special Events|Time Attack|$)/i},{name:'FEATURE',re:/Ranked Feature Races([\s\S]*?)(?=Ranked Weekly Races|Free 2 Play Weekly Race|Special Events|Time Attack|$)/i},{name:'WEEKLY',re:/Ranked Weekly Races([\s\S]*?)(?=Free 2 Play Weekly Race|Special Events|Time Attack|$)/i}];for(const sec of sections){const mm=t.match(sec.re);if(!mm)continue;const combo=/([A-Za-z0-9+& .\-'\/]{2,70})\s*(?:@| at )\s*([A-Za-z0-9 .\-'\/]{2,70})/gi;let c;while((c=combo.exec(mm[1])))add(c[1].replace(/^[-•\s]+/,''),c[2].split(/\n|  /)[0],sec.name)}
 const narr=t.match(/Ranked Multiplayer([\s\S]*?)(?=Special Events|Time Attack|DTM Esports|$)/i)?.[1]||'';const nr=/([A-Z][A-Za-z0-9+& .\-'\/]{1,50}?)\s+(?:heads to|at)\s+([A-Z][A-Za-z0-9 .\-'\/]{2,50})/g;let n;while((n=nr.exec(narr)))add(n[1],n[2].split(/,|\.|\n/)[0],'SPRINT');
 const free=t.match(/Free 2 Play Weekly Race([\s\S]*?)(?=Ranked Multiplayer|Ranked Sprint Races|Special Events|$)/i)?.[1]||'';if(free){const cls=free.match(/Class:\s*([^\n]+)/i)?.[1]?.trim(),car=free.match(/Car:\s*([^\n]+)/i)?.[1]?.trim(),track=free.match(/Track:\s*([^\n]+)/i)?.[1]?.trim();if(track&&(cls||car))add(cls||car,track,'WEEKLY',2,'Miércoles')}
 return events.map(({_key,...e})=>e)
}
async function raceRoomWeekly(){let posts=[];try{const raw=await fetchText(RR_API),data=JSON.parse(raw);posts=data?.appnews?.newsitems||[]}catch{}let post=posts.filter(p=>/this week in raceroom|ranked multiplayer|ranked schedule|weekly schedule/i.test((p.title||'')+' '+(p.contents||''))).sort((a,b)=>(b.date||0)-(a.date||0))[0];if(post){const published=new Date((post.date||Math.floor(Date.now()/1000))*1000),t=text(decode(post.contents||'').replace(/\[\/?[a-z][^\]]*\]/gi,' ')),xs=parseRRBlock(t,published,post.url||RR_STEAM);if(xs.length)return xs}const html=await fetchText(RR_STEAM),t=text(html);return parseRRBlock(t,new Date(),RR_STEAM)}

export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');const items=[],sources=[];for(const [name,fn] of [['RaceControl',raceControlDaily],['Le Mans Ultimate',lmuSpecial],['RaceRoom',raceRoomWeekly],['Assetto Corsa EVO',assettoCorsaEvoDaily]]){try{const xs=await fn();items.push(...xs);sources.push({name,status:'ok',count:xs.length,checkedAt:nowIso()})}catch(e){sources.push({name,status:'error',count:0,message:String(e.message||e),checkedAt:nowIso()})}}const seen=new Set(),unique=items.filter(e=>{if(seen.has(e.id))return false;seen.add(e.id);return true}).sort((a,b)=>new Date(a.start)-new Date(b.start));res.status(200).json({items:unique,sources,updatedAt:nowIso(),mode:'self-contained-v20'})}
